version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: counter-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: counter-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tfserving:
    image: tensorflow/serving
    container_name: counter-tfserving
    ports:
      - "8501:8501"
    volumes:
      - ./tmp/model:/models
    environment:
      MODEL_NAME: ${TF_MODEL_NAME}
      OMP_NUM_THREADS: ${OMP_NUM_THREADS:-2}
      TENSORFLOW_INTRA_OP_PARALLELISM: ${TF_INTRA_OP_THREADS:-2}

  app:
    build: .
    container_name: counter-app
    depends_on:
      - postgres
      - mongo
      - tfserving
    ports:
      - "5000:5000"
    environment:
      MODEL_TYPE: ${MODEL_TYPE}
      COUNT_BACKEND_TYPE: ${COUNT_BACKEND_TYPE}

      # Postgres
      DATABASE_URL: ${DATABASE_URL}

      # Mongo
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}

      # TensorFlow
      TFS_HOST: tfserving
      TFS_PORT: 8501
      MODEL_NAME: ${TF_MODEL_NAME}

volumes:
  postgres_data:
  mongo_data: